### PR TITLE
Feature/swift 5.0

### PR DESCRIPTION
**Pull request by christoff-1992**
Migrate to Swift 5.0

### CODE REVIEW

**Comment by zenangst** [comment]
@christoff-1992 seems like Travis needs an update for the tests to work. We can keep this PR open for a little while until CI's start updating to the newest stable releases.

**Comment by zenangst** [comment]
Oh, so they should actually support it already if we use the beta. Interesting :)

**Comment by zenangst** [comment]
@christoff-1992 I think you need to update the travis configuration to run on a newer version of tvOS.

```
Apple TV,OS=12.2
```

**Comment by christoff-1992** [comment]
@zenangst ahh nice thanks! .. I saw that they had the updated OSX image but didn't realise I needed to update the TV OS version. As spoken about il also remove the references to the watchOS before I commit anything pending a review.

**Comment by zenangst** [comment]
@christoff-1992 I think we can merge this badboy :)

**Pull request merged**
